#!/bin/sh
name=$1
description=${2:-${name}}
status=${3:-APPROVED}
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: $AUTH' -d "{ \"description\": \"$description\",  \"name\": \"$name\", \"status\": \"$status\" }" "${EGO_URL}/groups"
