#!/bin/sh
#set -x
name=$1
type=${2:-groups}
id=$(./find_id $name $type)

if [ -z "$id" ]; then
   echo "Can't find any $type with name $name"
else
   curl -s -X DELETE --header 'Accept: application/json' --header "Authorization:$AUTH" "http://localhost:9082/${type}/$id" | jq -r .
fi
