#!/bin/sh
name=$1
type=${2:-policies}
curl -s -X GET --header 'Accept: application/json' --header "Authorization:$AUTH" "${EGO_URL}/${type}?query=$name" | jq -r ".resultSet[] | if .name==\"$name\" then .id else empty end"
