#!/bin/sh
name=$1
policy_id=$(./find_id $name policies) 
echo "groups";echo "--"
curl -s -X GET --header 'Accept: application/json' --header "Authorization:$AUTH" "${EGO_URL}/policies/${policy_id}/groups" | jq .
echo
echo "users";echo "--"
curl -s -X GET --header 'Accept: application/json' --header "Authorization:$AUTH" "${EGO_URL}/policies/${policy_id}/users" | jq .
